time_zone: Beijing

super_admin:
  email: admin@example.com

website_GPG_key_ID: '99999999'
two_step_encryption_key: '99999999999999999999999999999999'

#
# 1 website and bastion_host in same host
#
Arch_mode: 1
Arch_mode_one:
  user: dev
