---

# Include OS-specific installation tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: user.yml

- include: ssh_key.yml

- include: gpg2_key.yml
