---

- name: "Ensure {{ gpg2_key_basedir }} config directory exists with right permissions"
  file:
    dest: "~/{{ gpg2_key_basedir }}"
    state: directory
    mode: 0700
  become: yes
  become_user: "{{ gpg2_key_user }}"