---

# Include OS-specific installation tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: common.yml

- include: generate.yml
  when: gpg2_key_action == 'generate'

- include: import.yml
  when: gpg2_key_action == 'import'
