---

- name: "Ensure {{ ssh_key_basedir }} config directory exists with right permissions"
  file:
    dest: "~/{{ ssh_key_basedir }}"
    state: directory
    mode: 0700
  become: yes
  become_user: "{{ ssh_key_user }}"
