---
dependencies:
  - role: shrikeh.haveged
    when: gpg_key_mgr_install_haveged

galaxy_info:
  author: vkill
  description: GPG Key
  company: vkill

  license: license ((BSD, MIT))

  min_ansible_version: 1.8

  platforms:
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags:
    - gpg
