- name: Replace ssh_key_public
  copy:
    src: "{{ user_ssh_key_public_file }}"
    dest: "~/{{ ssh_key_path }}/{{ ssh_key_public_file }}"
    backup: True
  become: yes
  become_user: "{{ ssh_user }}"
  when:
    - user_ssh_key_private_file is defined and user_ssh_key_private_file|length > 0
    - user_ssh_key_public_file is defined and user_ssh_key_public_file|length > 0

- name: Replace ssh_key_private
  copy:
    src: "{{ user_ssh_key_private_file }}"
    dest: "~/{{ ssh_key_path }}/{{ ssh_key_private_file }}"
    backup: True
  become: yes
  become_user: "{{ ssh_user }}"
  when:
    - user_ssh_key_private_file is defined and user_ssh_key_private_file|length > 0
    - user_ssh_key_public_file is defined and user_ssh_key_public_file|length > 0

- name: Register stat with ssh_key_public_file
  stat:
    path: "~/{{ ssh_key_path }}/{{ ssh_key_public_file }}"
  register: stat
  become: yes
  become_user: "{{ ssh_user }}"

- name: Ensure the ssh public key exists
  fail:
    msg: >
      The ssh public key ({{ stat.stat.path if stat.stat.exists == True else '' }}) should exists and can read it
  when: stat.stat.exists == False or stat.stat.rusr is not defined or stat.stat.rusr == False or stat.stat.size == 0
