---
- name: Run 'apt-get update'
  apt: update_cache=yes

- name: Update all packages
  apt: upgrade=dist

- name: Install basic packages
  apt: name={{item}} state=present
  with_items:
    - make
    - gcc
    - openssl
    - libssl-dev
    - unzip
    - imagemagick
    - libmagickwand-dev
    - libxml2-dev
    - libxslt-dev
    - curl
    - monit
