
super_admin_email: "admin@example.com"

devise_two_factor_otp_secret_encryption_key: "99999999999999999999999999999999"

time_zone: "Asia/Shanghai"

web_url:
  host: "127.0.0.1"
  port: "3000"

web_db:
  adapter: "mysql2"
  host: "127.0.0.1"
  username: "root"
  password: ""
  database: "ssh_bastion_development"

web_smtp:
  host: "127.0.0.1"
  port: "1025"

web_redis:
  host: "127.0.0.1"
  port: "6379"
