source 'https://rubygems.org'

gem 'rails', '=5.0.0.beta3'
gem 'mysql2', '~> 0.4.3'

gem 'sprockets', '~> 4.0.0.beta2'
gem 'sass-rails', '~> 6.0.0.beta1'
gem 'uglifier', '~> 2.7.2'
gem 'coffee-rails', '~> 4.1.1'

gem 'jquery-rails', '~> 4.1.0'
gem 'turbolinks', '~> 5.0.0.beta2'

gem 'jbuilder', '~> 2.4.1'

gem 'puma', '~> 3.0.2', require: false

gem 'dotenv-rails', '~> 2.1.0'

gem 'config', '~> 1.1.0'

gem 'rails-i18n', '~> 5.0.0.beta3'

gem 'nokogiri', '~> 1.6.8.rc3' #gpgme and nokogiri require conflict
gem 'gpgme', '~> 2.0.12'

gem 'devise', '~> 4.0.0.rc2'
gem 'devise-i18n', '~> 1.0.1'
gem 'devise-bootstrap-views', '~> 0.0.8'

gem 'attr_encrypted', '~> 3.0.1'
gem 'devise-two-factor', github: 'colorfulberry/devise-two-factor',
                         branch: 'devise-4', ref: 'fc93fb4a7a171d4ae1bfc055b29fc95574a18106'

gem 'switch_user', '~> 1.2.1'

gem 'activevalidators', '~> 3.0.0'

group :development, :test do
  gem 'byebug', '~> 8.2.2'

  gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner',
                          branch: 'master', ref: 'f318781a77228f5999f5f2371c12f59089c141f3',
                          require: false
  gem 'factory_girl_rails', '~> 4.6.0', require: false
  gem 'ffaker', '~> 2.2.0', require: false

  gem 'pry-rails', '~> 0.3.4'
end

group :development do
  gem 'web-console', '~> 3.1.1'
  gem 'listen', '~> 3.0.6'
  gem 'spring', '~> 1.6.4'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'parallel_tests', '~> 2.5.0'
end

group :test do
  gem 'rspec-rails', '~> 3.5.0.beta3', require: false

  gem 'capybara', '~> 2.6.2', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

